#!/usr/bin/env node
// Builds assets/js/sample-data.js (embedded demo data so the dashboard opens populated, even from file://).
// Scans samples/ATS_Program_SAMPLE/** recursively and groups workbooks into portfolios exactly like the app does.
// usage: node tools/build_sample_js.js
const fs = require('fs'), path = require('path');
const root = path.resolve(__dirname, '..');
global.window = global;
global.XLSX = require(path.join(root, 'assets/lib/xlsx.full.min.js'));
['core.js', 'kpi-data.js', 'raid.js'].forEach((f) => require(path.join(root, 'assets/js', f)));
const poapPath = path.join(root, 'assets/js/poap.js');
if (fs.existsSync(poapPath)) { try { require(poapPath); } catch (e) { console.warn('poap.js failed to load in node:', e.message); } }
const ATS = global.ATS;

const base = path.join(root, 'samples', 'ATS_Program_SAMPLE');
const files = [];
(function walk(d, rel) {
  fs.readdirSync(d, { withFileTypes: true }).forEach((e) => {
    if (e.name.startsWith('.') || e.name.startsWith('~$')) return;
    if (e.isDirectory()) walk(path.join(d, e.name), rel ? rel + '/' + e.name : e.name);
    else if (/\.xlsx$/i.test(e.name)) files.push({ full: path.join(d, e.name), name: e.name, dir: rel });
  });
})(base, '');

const items = [];
files.forEach((f) => {
  const wb = XLSX.read(fs.readFileSync(f.full), { type: 'buffer', cellDates: true });
  let kind = null;
  if (ATS.kpi.detect(wb)) kind = 'kpi'; else if (ATS.poap && ATS.poap.detect(wb)) kind = 'poap'; else if (ATS.raid.detect(wb)) kind = 'raid';
  if (!kind) { console.warn('skipped', f.dir + '/' + f.name); return; }
  const parsed = ATS[kind].parse(wb);
  const sz = kind === 'kpi' ? parsed.snapshots.length + parsed.defects.length : kind === 'poap' ? (parsed.plan || []).length : parsed.risks.length + parsed.issues.length;
  items.push({ kind, parsed, dir: f.dir, fileName: f.name, ts: fs.statSync(f.full).mtimeMs, sz });
});

const groups = ATS.groupPortfolios(items);
const out = { portfolios: [], files: [] };
groups.forEach((g) => {
  out.portfolios.push({ name: g.name, dir: g.dir, kpi: g.kpi || null, poap: g.poap || null, raid: g.raid || null });
  (g._items || []).forEach((it) => out.files.push({ name: (g.dir ? g.dir + '/' : '') + it.fileName, kind: it.kind, portfolio: g.name, note: ATS[it.kind].describe ? ATS[it.kind].describe(it.parsed) : '' }));
  console.log('✓', g.name.padEnd(28), g.kpi ? ATS.kpi.describe(g.kpi) : '-', '| POAP', g.poap ? g.poap.plan.length + ' bars' : '–', '| RAID', g.raid ? g.raid.risks.length + ' risks' : '–');
});
fs.writeFileSync(path.join(root, 'assets/js/sample-data.js'), '/* generated by tools/build_sample_js.js — embedded sample data */\nwindow.ATS_SAMPLE = ' + JSON.stringify(out) + ';\n');
console.log('wrote assets/js/sample-data.js', (fs.statSync(path.join(root, 'assets/js/sample-data.js')).size / 1024).toFixed(0) + ' KB,', out.portfolios.length, 'portfolio(s)');
